//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Adoption_system.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class ChildParent
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int ParentID { get; set; }
        [Required]
        public string ParentName { get; set; }
        [Required]
        public string ParentSurname { get; set; }
        [Required]
        public string CellPhone { get; set; }
        [Required]
        public string Email { get; set; }
        [Required]
        public string ChildName { get; set; }
        [Required]
        public string ChildSurname { get; set; }
        [Required]
        public int ChildAge { get; set; }
        [Required]
        public string Gender { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        [Required]
        public string Race { get; set; }
        [Required]
        public string Question { get; set; }
        [Required]
        public string Reason { get; set; }
    }
}
